apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: techtrends
  type: LoadBalancer
status:
  loadBalancer: {}
