apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  strategy: {}
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          pullPolicy: {{ .Values.image.pullPolicy }}
          name: techtrends
          ports:
            - containerPort: {{ .Values.image.containerPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
status: {}
