apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
  name: techtrends-balancer
  namespace: sandbox
spec:
  ports:
    - port: 6111
      protocol: TCP
      targetPort: 3111
  selector:
    app: techtrends
  type: LoadBalancer
status:
  loadBalancer: {}
