namespace:
  name: sandbox

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: birajpoddar/techtrends
  tag: latest
  pullPolicy: IfNotPresent
  containerPort: 3111

replicaCount: 1

resources:
  requests:
    memory: 64Mi
    CPU: 250m
  limits:
    memory: 128Mi
    CPU: 500m

livenessProbe:
  path: /healthz
  port: {{ .Values.image.containerPort }}

readinessProbe:
  path: /healthz
  port: {{ .Values.image/containerPort }}
